### ISSUE TITLE
rpm-ostree is a bit slow when installed this

### ISSUE THREAD

**Issue by wolf-yuan-6115** [CheariX/silverblue-akmods-keys#10]
As the title said, every time I ran `rpm-ostree install ...`, the build script was rerun even if I didn't touch Nvidia modules.
This leads to my `rpm-ostree` being stuck at `Running Post scripts`

**Comment by CheariX** [comment]
Hm... since I installed this package, I have never tried a comparison. 
To be honest, I have no idea how to fix this...

I know that each nvidia and each kernel update requires the recompilation of the nvidia modules, which in turn starts their signing. However, the signing itself should be relatively fast.

Can you somehow describe what "a bit slow" means? Do we talk about a second, a minute, or a couple of minutes?
What other packages are installed along with your desired package?

Maybe you could try to measure it (1. `time rpm-ostree install x` -> `rpm-ostree rollback` -> `rpm-ostree uninstall akmodes-keys && time rpm-ostree install x`).

**Comment by wolf-yuan-6115** [comment]
I decided to turn off my Nvidia card on my laptop because I rarely use it. I am closing this issue now.

**Comment by wolf-yuan-6115** [comment]
But I appreciate your work! Secure boot does work when this package is installed!
