### ISSUE TITLE
Correct steps

### ISSUE THREAD

**Issue by telometto** [CheariX/silverblue-akmods-keys#7]
Not an issue per se, so forgive me for opening one, but I was wondering about what the correct procedure is when executing the steps in your readme.
- Are the commands supposed to be ran as `sudo`?
- Should one do the steps _first_ and _then_ install `akmods` and `xorg-x11-drv-nvidia`?

Thanks!

**Comment by CheariX** [comment]
Hi,

- Yes, `setup.sh` must be executed with `sudo` since it needs access to your currently deployed mok (`/etc/pki/akmods/{private,certs}`.
- TLDR: the order should not make a difference. If you installed the nvidia driver first, they are not signed not your next boot. If you afterward install `akmods-keys`, the nvidia driver will be *reinstalled*, i.e. signed, subsequently/automatically.
If you install `akmods-nvidia` first, and then nvidia, the driver is directly signed.

Hope that helps!

**Comment by telometto** [comment]
@CheariX perfect! Thanks a lot for clearing that up 😊
